//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERInventario_BDLC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS_HISTORICO
    {
        public int HIST_ID { get; set; }
        public Nullable<int> PROD_ID { get; set; }
        public Nullable<System.DateTime> HIST_FECHA_MODIFICACION { get; set; }
        public Nullable<long> HIST_STOCK { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
