//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MERInventario_BDLC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.PRODUCTOS_HISTORICO = new HashSet<PRODUCTOS_HISTORICO>();
        }
        [Display(Name ="ID Producto")]
        public int PROD_ID { get; set; }
        [Display(Name = "Categoría")]
        public Nullable<int> CAT_ID { get; set; }
        [Display(Name = "Proveedor")]
        public Nullable<int> PROV_ID { get; set; }
        [Display(Name = "Marca")]
        public Nullable<int> MAR_ID { get; set; }
        [Display(Name = "Descripción Producto")]
        public string PROD_DESCRIPCION { get; set; }
        [Display(Name = "Cantidad")]
        public long PROD_CANTIDAD { get; set; }
        [Display(Name = "Precio Unitario")]
        public double PROD_PRECIO_UNI { get; set; }
        [Display(Name = "Largo")]
        public double PROD_LARGO { get; set; }
        [Display(Name = "Ancho")]
        public double PROD_ANCHO { get; set; }
        [Display(Name = "Profundidad")]
        public double PROD_PROFUNDIDAD { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual MARCA MARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTOS_HISTORICO> PRODUCTOS_HISTORICO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
